### ISSUE TITLE
Linkage 'Z' uses the same cluster more than once

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/heatmap-scatter-dash#100]
Seems to happen a lot?
```
Traceback (most recent call last):
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/dash/dash.py", line 541, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/dash/dash.py", line 498, in add_context
    output_value = func(*args, **kwargs)
  File "/Users/chuck/github/refinery-platform/heatmap-scatter-dash/context/app/app_callbacks.py", line 80, in _update_heatmap
    cluster_cols=self._cluster_cols)
  File "/Users/chuck/github/refinery-platform/heatmap-scatter-dash/context/app/utils/cluster.py", line 30, in cluster
    col_label_order = _order_rows(dataframe.T, cluster_cols)
  File "/Users/chuck/github/refinery-platform/heatmap-scatter-dash/context/app/utils/cluster.py", line 11, in _order_rows
    rows_order = leaves_list(rows_linkage).tolist()
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 1711, in leaves_list
    is_valid_linkage(Z, throw=True, name='Z')
  File "/Users/chuck/anaconda3/envs/dash/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 1421, in is_valid_linkage
    % name_str)
ValueError: Linkage 'Z' uses the same cluster more than once.
```

**Comment by mccalluc** [comment]
Have not seen this recently... closing for now, but feel free to reopen.
