### ISSUE TITLE
v0.1.1: UnicodeDecode Error while launching through Refinery

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/heatmap-scatter-dash#159]
Dataset Used: https://www.dropbox.com/s/59i4mot0qhy2xdl/heatmap_scatterplot_demo.csv?dl=0

`docker logs`:
```
(refinery-platform)vagrant@refinery:/vagrant/refinery$ docker logs f1ef0d37de0d
args from __main__: demo: False
files: [<_io.TextIOWrapper name='/refinery-datanormalizedCounts.csv.gz' mode='r' encoding='UTF-8'>]
diffs: [<_io.TextIOWrapper name='/refinery-dataDE_H460_treament_ko_vs_wt_all.csv.gz' mode='r' encoding='UTF-8'>, <_io.TextIOWrapper name='/refinery-dataDE_H2009_treament_ko_vs_wt_all.csv.gz' mode='r' encoding='UTF-8'>]
most_variable_rows: 500
port: 80
profile: False
html_error: False
debug: False
api_prefix: /visualizations/HeatmapScatterplot-653bca82-acdc-4dc7-9627-30288a63177e/
Traceback (most recent call last):
  File "app_runner_refinery.py", line 111, in <module>
    app_runner.main(args)
  File "/app_runner.py", line 91, in main
    server = init(args=args, parser=parser)
  File "/app_runner.py", line 44, in init
    dataframes = file_dataframes(args.files)
  File "/app_runner.py", line 22, in file_dataframes
    frames.append(tabular.parse(file))
  File "/app/utils/tabular.py", line 11, in parse
    dialect = Sniffer().sniff(file.readline())
  File "/usr/local/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by mccalluc** [comment]
Good catch! 
```
    # We could use read_csv with separator=None...
    # but that requires the python parser, which seems to be about
    # three times as slow as the c parser.
    dialect = Sniffer().sniff(file.readline())
    file.seek(0)
    with warnings.catch_warnings():
        # https://github.com/pandas-dev/pandas/issues/18845
        # pandas raises unnecessary warnings.
        warnings.simplefilter("ignore")
        dataframe = read_csv(
            file,
            index_col=0 if col_zero_index else None,
            dialect=dialect
        )
```
- Pandas `read_csv` claims it can handle gzip... But I'm trying to sniff the delimiter first (because if I pre-sniff, I can use the C parser, and that's a lot faster.), and that sniffing can't handle zipped files. so...
- Hopefully there is an option to unzip just the first few K? But first look at the file extension to see if that's necessary.
