### ISSUE TITLE
TypeError on POST to /_dash-update-component

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/heatmap-scatter-dash#76]
@mccalluc  I noticed this after getting the CSRF stuff working earlier. Using docker image: `mccalluc/heatmap_scatter_dash:v0.0.9`

This could have very well already been fixed!

```
172.17.0.1 - - [09/Jan/2018 17:49:30] "POST /_dash-update-component HTTP/1.1" 500 -
[2018-01-09 17:49:30,053] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/dash/dash.py", line 541, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/usr/local/lib/python3.6/site-packages/dash/dash.py", line 498, in add_context
    output_value = func(*args, **kwargs)
  File "/app/app_callbacks.py", line 73, in _update_heatmap
    selected_genes_ids_json
  File "/app/app_gene_callbacks.py", line 151, in _filter_by_genes_ids_json
    selected_genes_ids = json.loads(json_list)
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
```

**Comment by mccalluc** [comment]
Thanks: I think all of those are handled now: In this case the fix was:
```python
    def _filter_by_gene_ids_json(self, dataframe, json_list):
        if json_list:
            selected_gene_ids = json.loads(json_list)
            return dataframe.reindex(selected_gene_ids)
        else:
            return dataframe
```

(But the real, real fix is to get a new release out!)
